# **Week 2 ARTS**

## **Tips**

### 关于此错误的处理  QueuePool limit of size <x> overflow <y> reached, connection timed out, timeout <z>¶

使用flask sqlalchemy的QueuePool时出现该错误，对于该错误的详细解释参考

[sqlalchemy 官方文档](http://docs.sqlalchemy.org/en/latest/errors.html#error-3o7r)

参照描述文档，可以推断是由于QueuePool中的资源耗尽为止，但是按照正常逻辑flask_sqlalchemy并不需要单独设置显示的执行session.close(),

经过各种资料搜索，最终发现是由于在flask以debug模式启动时，在request结束时并不会执行teardown_appcontext中的session close,

也就是说teardown_appcontext在debug模式下并不会保证执行完成，通过自己在本地调试，发现确实如此。

将debug设置为true时该错误会在pool size + max overflow上限时复现该错误, 在debug设置为false时该错误不会出现。下面这种文章中给了点思路：

[textdown_appcontext](https://my.oschina.net/u/2357606/blog/407473)
